### ISSUE TITLE
admin rights in just one collection?

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#365]
Is it possible to assign admin rights to the owner of a collection? This would allow them to do advanced searches and bulk updates which otherwise are not available to them. At the same time, we don't want to give them general admin rights to the whole of NABU.

**Comment by nthieberger** [comment]
The problem is that most users should not be able to do bulk updates as they could do severe damage. And we have not 'undo' function

**Comment by enwardy** [comment]
but can we make advanced search available (to all users) WITHOUT the subsequent 'bulk update' option? @JonoGillett

**Comment by johnf** [comment]
@nthieberger I'm pretty sure this is how things currently work, please reopen if we need to change something
