### ISSUE TITLE
Missing 'edit collection' link for users with edit access

### ISSUE THREAD

**Issue by jangari** [paradisec-archive/nabu#383]
I've just discovered there there is a button missing on the collection page for users that have been given edit access to that collection.

I was just testing to see whether a user with edit access over a whole collection was thereby given edit access to all items within that collection, which is the case, but in doing so I found that on the collection page itself, there is no 'edit collection' link as there is for admins.

Manually navigating to the edit page (http://catalog.paradisec.org.au/collections/{coll_ID}/edit) brings up the correct edit page, so they do in fact have edit access, but there is no link. 

See the screenshots below. The first is what a user with edit access sees, the second is what they should see (or, what an admin sees for a collection page).

![screen shot 2014-10-23 at 12 57 31 pm](https://cloud.githubusercontent.com/assets/1875291/4747218/45d1ea92-5a58-11e4-8887-4f8f22e80251.png)
![screen shot 2014-10-23 at 12 58 00 pm](https://cloud.githubusercontent.com/assets/1875291/4747220/4a465fb8-5a58-11e4-82d5-19a6412dccca.png)

**Comment by johnf** [comment]
I actually fixed this last week :)
