### ISSUE TITLE
Delete files

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#505]
Please delete any files with the extension .qua (see JW1 collection), and also any with extension .exp.xml. I have deleted some from JW1 so hope that hasn't caused any problems.

**Comment by enwardy** [comment]
@JonoGillett was this done?

**Comment by agrimmtt** [comment]
@nthieberger I've attached an Excel file of files to delete. Can you confirm that that you're happy for all of the essences and files listed in this spreadsheet, including those for DD1-047, being deleted?

[Files to delete Nabu issue 505.xlsx](https://github.com/nabu-catalog/nabu/files/2221339/Files.to.delete.Nabu.issue.505.xlsx)

**Comment by nthieberger** [comment]
Yes, please delete these files. Thanks.
Nick

**Comment by NickWardPDSC** [comment]
looks like all .qua and all .exp.xml files have been deleted

**Comment by NickWardPDSC** [comment]
...however there are now some other files (and the folder they are in) that need to be deleted, and that I am unable to delete from the catalog:

./LPF/WD053/LPF-WD053-IMG_02.jpg.cyberducksegment
./LPF/WD053/LPF-WD053-IMG_02.jpg.cyberducksegment/5.cyberducksegment
./LPF/WD053/LPF-WD053-IMG_02.jpg.cyberducksegment/3.cyberducksegment
./LPF/WD053/LPF-WD053-IMG_02.jpg.cyberducksegment/4.cyberducksegment
./LPF/WD053/LPF-WD053-IMG_02.jpg.cyberducksegment/2.cyberducksegment
./LPF/WD053/LPF-WD053-IMG_02.jpg.cyberducksegment/1.cyberducksegment

**Comment by johnf** [comment]
I already have a task to clean up the catalog once we launch the new ingest system
