### ISSUE TITLE
Items DELETED in Nabu but REMAINING in directory

### ISSUE THREAD

**Issue by enwardy** [paradisec-archive/nabu#651]
items have been deleted via the catalog in the collection AC3, but they are still showing up in the collection directory. Currently 65 Items showing in AC3 directory, but only 41 Items showing in catalog. 

Items deleted in the catalog should also delete the corresponding directory entry?

**Comment by enwardy** [comment]
still outstanding. There look to be plenty of items (and Collection/s, e.g. AGRIMM20160224) deleted from the catalog but still showing up in the directory. E.g. (apart from AC3, as above) HOMSEY-2nd

**Comment by enwardy** [comment]
I will test and hopefully resolve this..

**Comment by nthieberger** [comment]
We can delete these from the directory if they are not referenced in NABU

**Comment by nthieberger** [comment]
I deleted AGRIMM20160224 in the filesystem and HOMSEY in NABU

**Comment by nthieberger** [comment]
Jono can we delete ST1 (your test collection)?

**Comment by nthieberger** [comment]
Also to delete : collections test, test2 and test3; ZZZZZ.

Does anyone know what the directory 'dropbox_upload' is for?

**Comment by JonoGillett** [comment]
dropbox_upload can be removed - it was used for the CLC recovery process to upload the unknown recovered files for investigation

**Comment by nthieberger** [comment]
Which of those collections do you want to keep?

**Comment by JonoGillett** [comment]
Sorry - I started replying to ST1 but then you added more comments after :) just ST1 is all I'm interested in keeping

**Comment by nthieberger** [comment]
OK, the substantive issue is still true, not all files/directories are deleted when the item is deleted from NABU. But they should be.

**Comment by JonoGillett** [comment]
So it seems the issue is that when we delete from Nabu the directory structure and any PDSC_ADMIN files are not removed.

Can you confirm the desired behaviours for each of the types here?

**Delete Collection**
Remove all trace of the collection - including the collection folder, all items, essences and admin files

**Delete Item**
Remove all traces of the item - including the item folder, all essences and admin files

**Delete Essence**
Remove essence and any associated admin files (e.g. spectrum or thumbnails)

**Comment by JonoGillett** [comment]
@nthieberger @AmandaPDSC any thoughts/comments on the above? Let me know and I'll proceed with the changes

**Comment by AmandaPDSC** [comment]
Yes the above represents what we need - @nthieberger do you agree?

**Comment by johnf** [comment]
Should no longer be relevant in S3 land
