### ISSUE TITLE
private items need to be completely hidden

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#664]
Searching for items in DWU gets 183 hits for a general user, but only 12 of these are not private. A collection view shows that there are 183 items, but only allows the user to see 12 of them. The search should only tell the user there are 12 items, not 183.

**Comment by JonoGillett** [comment]
@nthieberger does this happen in all the different searches, or only specific ones?

i.e. Basic search, Advanced Search and Builder

**Comment by johnf** [comment]
I've confirmed this doesn't happen in new search
