### ISSUE TITLE
Sign-in bug?

### ISSUE THREAD

**Issue by AmandaPDSC** [paradisec-archive/nabu#676]
User Mark Post reports:

I have a problem in which I'm unable to sign in to my account in PARADISEC. Each time I try to login I need to do a "reset password" request in order to login. Once I do reset my password, I can actually login and do whatever. But the next time I try to login, using the same information, the same behaviour occurs. This is in both Firefox with lots of privacy features enabled, in Chrome with few privacy features enabled, and in a factory-settings instance of Internet Explorer. Can you help?

**Comment by AmandaPDSC** [comment]
Other users with login problems: Rachel Nordlinger and Naijing Liu - admins resetting the password has not worked

**Comment by johnf** [comment]
@AmandaPDSC do you know if this is still an issue?

**Comment by AmandaPDSC** [comment]
I haven't heard that this is an issue for some time @juliamiller and @NickWardPDSC have you?

**Comment by NickWardPDSC** [comment]
Agree , I think this is an old issue, haven’t heard about it happening recently
Nick

________________________________
