### ISSUE TITLE
Advanced search does not search all fields? Want to search for Funding body and Grant Identifier

### ISSUE THREAD

**Issue by juliamiller** [paradisec-archive/nabu#682]
When doing an advanced search across COLLECTIONS, using the fields "Funding body" (ARC - Australian Research Council) and "Grant identifier" (CE140100041) I get 496 results, which I believe is the number of collections we have in PARADISEC. So it looks like the targeted search fields are not getting searched. 

Oddly, when doing this search just in the COLLECTIONS tab in the browser using the search field there, the grant ID “CE140100041” as the search term gets 72 hits, which all seem to be ones I have added the info about the ARC and grant ID into those fields, and added this info into the comments field: "This research project, including archiving, was funded by the ARC Centre of Excellence for the Dynamics of Language - Grant ID: CE140100041 [ 2014 - 2020 ] http://purl.org/au-research/grants/arc/CE140100041"

When I search at the ITEM level in an advanced search, I pasted in the above text that is in the searchable COMMENTS field ("This research project, including archiving, was funded by the ARC Centre of Excellence for the Dynamics of Language - Grant ID: CE140100041 [ 2014 - 2020 ] http://purl.org/au-research/grants/arc/CE140100041") I get a return of 23,429 hits, which is all of our items in PARADISEC. So again no actual search  based on that field.

**Comment by johnf** [comment]
Fixed in new search
