### ISSUE TITLE
metadata spreadsheet import takes. long time

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#700]
I tried importing the spreadsheet, but it hangs, and then throws an error. It also has a note at the bottom saying it is waiting for google-analytics, is tha t the cause of the problem?

**Comment by johnf** [comment]
@nthieberger Could you send me a test spreadsheet to import? And remind me where the import section is

**Comment by johnf** [comment]
We moved from storing sessions in the database to using cookies. (The old database session table was 7GB in size)
This limits the amount of data in flash messages. The spreadsheet had lots of errors.
I now limit the response to 1000 characters

**Comment by nthieberger** [comment]
OK, I imported a wellformed spreadsheet without problems, thanks.

**Comment by NickWardPDSC** [comment]
metadata spreadsheet import is very unreliable and inconsistent lately. Mostly not working. eventually if you keep trying it *might* work. Eventually.

**Comment by johnf** [comment]
@NickWardPDSC I found the error in sentry and have fixed it. Should be good now

**Comment by NickWardPDSC** [comment]
[like]  Nicholas Ward reacted to your message:
________________________________
