### ISSUE TITLE
advanced search issues

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#751]
I can't enter a 'language as given', and I can't select a collector by typing the name. In Chrome.

**Comment by johnf** [comment]
@nthieberger Can you check if this is still an issue

**Comment by NickWardPDSC** [comment]
@johnf 
I've tested the two issues listed here by NickT, they appear to be resolved. However, I have another Advanced Search problem: searching by "Private:True/False" works for a collection search, and also works for item search in the results displayed, BUT doesn't work in the csv download of the Item search. No matter which option is chosen (Private:True or False), and which results display (correctly), when you download the csv, in either case it contains all 40,445 items, i.e. both Private and not-Private items.

**Comment by johnf** [comment]
Fix rolling out now, should also be faster
