### ISSUE TITLE
OAI feed

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#752]
The feed is giving an eror:

https://catalog.paradisec.org.au/oai/item?identifie=oai%3Aparadisec.org.au%3AAA1-002&metadataPrefix=olac&verb=GetRecord

<error code="badArgument">The request includes illegal arguments, is missing required arguments, includes a repeated argument, or values for arguments have an illegal syntax.</error>

**Comment by nthieberger** [comment]
Probably related, OLAC is no harvesting our feed (but that could be OLAC's problem):
http://www.language-archives.org/checks/paradisec.org.au

**Comment by johnf** [comment]
@nthieberger You're missing an r in the URL on the end of identifier. This link should work
https://catalog.paradisec.org.au/oai/item?identifier=oai%3Aparadisec.org.au%3AAA1-002&metadataPrefix=olac&verb=GetRecord

Regarding OLAC I wonder if this is related to the DNS issues. Let me chase that up via email

**Comment by nthieberger** [comment]
OK, the 'r' less version is what is given by the API link on the catalog:
Or you can get all the details of a single item of PARADISEC like this:
[https://catalog.paradisec.org.au/oai/item?verb=GetRecord&identifier=oai:paradisec.org.au:AA1-002&metadataPrefix=olac](https://catalog.paradisec.org.au/oai/item?identifie=oai%3Aparadisec.org.au%3AAA1-002&metadataPrefix=olac&verb=GetRecord)

While the text has the 'r', the link does not

**Comment by johnf** [comment]
Pushing a fix for the link now

**Comment by johnf** [comment]
I've validated ```https://catalog.paradisec.org.au/oai/item``` at ```http://www.language-archives.org/register/register.php```
With no errors.

@nthieberger I think you might have received an email.

Can you re-register?

It might have been DNS issues but they are now fixed
![image](https://github.com/nabu-catalog/nabu/assets/42590/67021ec9-9a00-4747-9299-af7aafbccbf8)

**Comment by nthieberger** [comment]
I validated again but did not get a registration request, I suspect OLAC is not operating propoerly and will ask them

**Comment by johnf** [comment]
@nthieberger did you here back from them?

**Comment by nthieberger** [comment]
No, they are as unresponsive as their site ...

**Comment by johnf** [comment]
Should be fixed now. @nthieberger Do we have to reregister or will they start crawling again by themseleves?
