### ISSUE TITLE
signed in depositors should not see the 'Upload metadata file' button

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#755]
Only admins should see this button in the dashboard

**Comment by johnf** [comment]
Fixed - will be deployed shortly

**Comment by AmandaPDSC** [comment]
non-admins seem to still be able to see the 'Upload metadata file' button, and they also shouldn't be able to see 'add new collection'. I just tried to login as my non-admin test user and I could click on 'add new collection' but then got the error: 
'You need to sign in or sign up before continuing.'

Could we just make both buttons not visible for non-admins?

**Comment by johnf** [comment]
Should be properly fixed now
