### ISSUE TITLE
advanced search bug

### ISSUE THREAD

**Issue by NickWardPDSC** [paradisec-archive/nabu#759]
I'm searching for all items in a collection (in order to bulk update them). 
Specifically, the MFE01 collection, in which there are 35 items. When I 'Advance Search' for "MFE01-" in item ID field, I get 64 search results, but then it won't let me display them all on one page (Error), and if I click through each page, that works for the first 3 pages, so 30 items, and then when I click 'Next' to go onto the fourth page, to try to view results 31-40, I get an Error message

**Comment by NickWardPDSC** [comment]
oh, and the same issue occurs if I do a Basic Search for "MFE01-"

**Comment by johnf** [comment]
This is fixed by the new search
