### ISSUE TITLE
Glitch refining search results

### ISSUE THREAD

**Issue by AmandaPDSC** [paradisec-archive/nabu#838]
When we use a collector name to refine a set of search results, changing the number of viewed records reverts to the original found search set, rather than the refined search set.

E.g. Basic item search on RB returns 262 results, refining to just the collector Reuben Brown refines to 74 results, then clicking 'Show 50' reverts to the first 50 of 262 results, but as a user, I expect it to show me the first 50 of 74.

**Comment by johnf** [comment]
@AmandaPDSC I noticed something similar recently and fixed it. This should work now. Let me know if you still notice issues
