### ISSUE TITLE
uppercase file extension ingest bug

### ISSUE THREAD

**Issue by NickWardPDSC** [paradisec-archive/nabu#842]
1. There was an image file in database but missing from S3 (SUY1-images-6136.JPG).

2. I got hold of a backup copy of the file, put it into incoming with the same filename, including uppercase file extension.

3. It processed successfully and has added the files to S3 as .tif and .jpg (lowercase). However, viewing from Nabu, the .tif file is visible, but the [absent] .JPG file has not been replaced with the [new] .jpg . 

I guess this is just the upper/lowercase extensions finding a gap in the ingest code? 

This would be an extremely rare sequence of events, possibly will never occur again, so it may not even need to be fixed in a general way. But for this specific file, obviously, it should be fixed, if you can?

**Comment by johnf** [comment]
@NickWardPDSC I've renamed all these in the DB as well as in S3 so DOI etc remain the same
