### ISSUE TITLE
just wondering about searching all essence files

### ISSUE THREAD

**Issue by nthieberger** [paradisec-archive/nabu#89]
Would it be possible to create an index of all essence files that could be searched from the catalog? This is a new task I know, but it could be useful. We have searchable (text or pdf) files as follows at the moment:
cha        39 
eaf       113 
lbl        30  
mxf        42 
pdf     5,034
pfs        40  
tab        40  
trs       188  
txt       359  
xml     6,546

**Comment by nthieberger** [comment]
It could be that we can leave this function to ALVEO - needs to be investigated by me, but if it is easy-ish to do then we could have it in NABU

**Comment by JonoGillett** [comment]
So to confirm, the idea here is:
step 1) index the contents of essence files where possible (e.g. the content of text and PDF files)
step 2) provide a new search tab and page dedicated to essence files

Is that correct?

**Comment by nthieberger** [comment]
could it be part of the advanced search to allow a free text search option?

**Comment by johnf** [comment]
Closed in favur of #757
